[
  "test.py::test_error_get_path"
]